id: ID61FFBF1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T00:22:46+00:00'
last_modified: '2022-06-08T13:21:14.332195+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23919
  title: གསུང་འབུམ། ཐང་སྟོང་རྒྱལ་པོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    083D:
      image_group_id: I3509
      title: ''
      total_pages: 572
      order: 1
      base_file: 083D.txt
    '8267':
      image_group_id: I3510
      title: ''
      total_pages: 572
      order: 2
      base_file: 8267.txt
    5FC8:
      image_group_id: I3511
      title: ''
      total_pages: 492
      order: 3
      base_file: 5FC8.txt
    A3A3:
      image_group_id: I3512
      title: ''
      total_pages: 654
      order: 4
      base_file: A3A3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
