id: ID61FFBF1
legacy_id: P010405
ocr_import_info:
  bdrc_scan_id: W23919
  source: bdrc
  ocr_info:
    timestamp: '2021-01-19T10:45:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:12:07.249686+00:00'
last_modified: 2022-09-02 13:13:47.011438
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23919
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23919
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཐང་སྟོང་རྒྱལ་པོ།
  author: གྲུབ་ཆེན་ཐང་སྟོང་རྒྱལ་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.8155824876596367
  ocr_word_median_confidence_index: 0.9
quality: null
bases:
  I3509:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3509
      total_pages: 572
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3509.txt
    statistics:
      ocr_word_median_confidence_index: 0.9
      ocr_word_mean_confidence_index: 0.8156901043480683
    legacy_id: v001
  I3511:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3511
      total_pages: 492
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3511.txt
    statistics:
      ocr_word_median_confidence_index: 0.9
      ocr_word_mean_confidence_index: 0.8086059458218549
    legacy_id: v003
  I3512:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3512
      total_pages: 654
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3512.txt
    statistics:
      ocr_word_median_confidence_index: 0.9
      ocr_word_mean_confidence_index: 0.8119383040168023
    legacy_id: v004
  I3510:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3510
      total_pages: 572
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3510.txt
    statistics:
      ocr_word_median_confidence_index: 0.91
      ocr_word_mean_confidence_index: 0.8279532427071037
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
